# general
title: Bet9ja Predicts Football Data Visualiser
author: SenseiFavour
description: ""
timezone: Europe/London

# urls
url: "http://footballdatadotorg.herokuapp.com"
baseurl: "/"

# exclude
exclude:
- node_modules
- Gruntfile.js
- package.json
- README.md
